#manually plotting y=sin(x) function without using any plotting modules

x1 =  ("----")
x2 =  ("------")
x3 =  ("--------")
x4 =  ("---------")
x5 =  ("-----------")
x6 =  ("-----------")
x7 =  ("------------")
x8 =  ("------------")
x9 =  ("-----------")
x10 = ("----------")
x11=  ("---------")
x12 = ("--------")
x13 = ("------")
x14 = ("----")
x15 = ("---")
x16 = ("---")
x17 = ("---")
x18 = ("----")
x19 = ("-----")
x20 = ("-------")
x21 = ("--------")
x22 = ("---------")
x23 = ("----------")
x24 = ("-----------")
x25 = ("----- -----")
x26 = ("-----------")
x27 = ("----------")
x28 = ("---------")
x29 = ("--------")
x30 = ("------")
x31=  ("-----") 



print('Plot for y=sin(x)')
print(x1)
print(x2)
print(x3)
print(x4)
print(x5)
print(x6)
print(x7)
print(x8)
print(x9)
print(x10)
print(x11)
print(x12)
print(x13)
print(x14)
print(x15)
print(x16)
print(x17)
print(x18)
print(x19)
print(x20)
print(x21)
print(x22)
print(x23)
print(x24)
print(x25)
print(x26)
print(x27)
print(x28)
print(x29)
print(x30)
print(x31)


#after days of soulsearching realized last minute that this seems to be the needed approach, hence the very manual last-minute solution. 

